CREATE TABLE db.products (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  POINT_ID BIGINT,
  PRICE BIGINT,
  AMOUNT BIGINT NOT NULL,
  NAME VARCHAR(45) NULL,
  DESCRIPTION VARCHAR (255) NULL ,
   PRIMARY KEY (ID),
  FOREIGN KEY (POINT_ID) REFERENCES points(ID)
 );

ALTER TABLE db.products MODIFY PRICE DOUBLE ;

ALTER TABLE db.products MODIFY AMOUNT DOUBLE ;